mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('weaponry/', include('weaponry.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='weaponry/', permanent=True)),
    path('tinymce/', include('tinymce.urls'))
,] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weaponry/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('soldiers/', views.soldiers, name='soldiers'),
    path('soldiers/<int:soldier_id>', views.soldier, name='soldier'),
    path('weapons/', views.WeaponListView.as_view(), name='weapons'),
    path('weapons/<int:pk>', views.WeaponDetailView.as_view(), name='weapon-detail'),
    path('search/', views.search, name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('add/add-weapon/', views.WeaponByAdminCreateView.as_view(), name='add-weapon'),
    path('soldiers/<int:soldier_id>/<uuid:pk>', views.WeaponByAdminDeleteView.as_view(), name='delete-weapon'),
    ]

weaponry/models.py
import uuid
from datetime import date
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from django.views.generic.edit import CreateView
# Create your models here.

class Weapon(models.Model):
    name = models.CharField('Name', max_length=50)
    country = models.CharField('Country', max_length=50)
    # description = models.TextField('Description', max_length=1000, help_text='Weapon description')
    description = HTMLField()
    cover = models.ImageField('Cover', upload_to='covers', null=True)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('weapon-detail', args=[str(self.id)])

class WeaponUnit(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID of a weapon')
    weapon = models.ForeignKey('Weapon', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField('Date', null=True, blank=True)
    # soldier = models.ForeignKey('Soldier', on_delete=models.SET_NULL, null=True)
    operator = models.ForeignKey('Soldier', on_delete=models.SET_NULL, null=True, blank=True)
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('a', 'Assigned'),
        ('n', 'Not assigned'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Status',
    )

    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.weapon.name} {self.operator} )'


class Soldier(models.Model):
    rank = models.CharField('Rank', max_length=50)
    first_name = models.CharField('Name', max_length=100)
    last_name = models.CharField('Last name', max_length=100)
    # description = HTMLField(default="")
    # description = models.TextField('Description', max_length=2000, default='')
    description = HTMLField()
    @property
    def display_weapons(self):
        return ', '.join(weapon.name for weapon in self.weapons.all()[:3])

    # display_weapons.short_descriptiopn = 'Weapons'
    class Meta:
        ordering = ['rank', 'first_name', 'last_name']

    def get_absolute_url(self):
        return reverse('soldier-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.rank}. {self.last_name}, {self.first_name}'

weaponry/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Weapon, Soldier, WeaponUnit
from django.contrib import messages
from django.contrib.auth.forms import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormMixin, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

def index(request):
    num_weapons = Weapon.objects.all().count()
    num_units = WeaponUnit.objects.all().count()
    num_units_available = WeaponUnit.objects.filter(status__exact='a').count()
    num_soldiers = Soldier.objects.count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_weapons': num_weapons,
        'num_units': num_units,
        'num_units_available': num_units_available,
        'num_soldiers': num_soldiers,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)

@login_required
def soldiers(request):
    paginator = Paginator(Soldier.objects.all(), 12)
    page_number = request.GET.get('page')
    paged_soldiers = paginator.get_page(page_number)
    # soldiers = Soldier.objects.all()
    context = {
        'soldiers': paged_soldiers
    }
    return render(request, 'soldiers.html', context=context)
# Create your views here.

def soldier(request, soldier_id):
    single_soldier = get_object_or_404(Soldier, pk=soldier_id)
    return render(request, 'soldier.html', {'soldier': single_soldier})


class WeaponListView(LoginRequiredMixin, generic.ListView):
    model = Weapon
    paginate_by = 6
    template_name = 'weapon_list.html'

class WeaponDetailView(generic.DetailView):
    model = Weapon
    template_name = 'weapon_detail.html'

def search(request):
    query = request.GET.get('query')
    search_results = Weapon.objects.filter(Q(name__icontains=query) |
                                        Q(description__icontains=query))
    return render(request, 'search.html', {'weapons': search_results, 'query':
        query})


class WeaponByAdminCreateView(LoginRequiredMixin, CreateView):
    model = WeaponUnit
    fields = ('weapon', 'due_back', 'status', 'operator')
    success_url = '/weaponry/'
    template_name = 'create_unit.html'
    def form_valid(self, form):
        form.instance.admin = self.request.user
        return super().form_valid(form)


class WeaponByAdminDeleteView(LoginRequiredMixin, DeleteView):
    model = WeaponUnit
    template_name = 'delete_weapon.html'

    def test_func(self):
        weapon = self.get_object()
        return self.request.user == weapon.admin

    def get_success_url(self):
        soldier_id = self.kwargs['soldier_id']
        return reverse_lazy('soldier', kwargs={'soldier_id': soldier_id})

weaponry/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% block title %}
<title>WEAPONRY</title>
{% endblock %}

<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous"
/>
<link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<!-- Add additional CSS in static file -->
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<!-- Navigation -->

<nav
        class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow"
>
    <div class="container">

        <a class="navbar-brand" href="/">
            <strong>WEAPONRY</a>
        </strong>
        <style>
      body {
        background-color: #909090;
      }


        </style>
        </head>
        <body>
        <header>
            <nav>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'weapons' %}">Weapons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'soldiers' %}">Soldiers</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'add-weapon' %}">Add Weapon Unit</a></li>
                        {% if user.is_authenticated %}
                        <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                                  clip-rule="evenodd"/>
                        </svg>
                        {{ user.get_username }}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link"
                                                href="{% url 'login' %}?next={{request.path}}">Login</a>
                        </li>
                        {% endif %}
                    </ul>

                    <form
                            class="form-inline my-2 my-lg-0"
                            action="{% url 'search' %}"
                            method="get"
                    >
                        <div class="input-group">
                            <input
                                    class="form-control mr-sm-2"
                                    type="search"
                                    placeholder="Search"
                                    aria-label="Search"
                                    name="query"
                            />
                            <button class="btn btn-info my-2 my-sm-0" type="submit">
                                Search
                            </button>
                        </div>
                    </form>
                </div>
    </div>
</nav>
<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}"
         role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}


    {% block content %}{% endblock %}
</div>

<script
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"
></script>
<script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"
></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"
></script>
</body>
</html>

weaponry/templates/create_unit.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Add a new weapon
            </legend>
            {{ form | crispy }}
            <button class="btn btn-outline-info" type="submit">Add</button>
        </fieldset>
    </form>
</div>
{% endblock %}

weaponry/templates/delete_weapon.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete a weapon</legend>
            <h2>Are you sure you want to delete {{ weaponunit.weapon.name }} and its information from the database?</h2>
            <h2>Operator: {{ weaponunit.operator }}</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">
                Yes, remove
            </button>
            <a class="btn btn-outline-secondary" href="{% url 'weapons' %}">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock content %}

weaponry/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Weaponry</h1>
<p>What's available right now:</p>
<ul>
    <li><strong>Weapons:</strong> {{ num_weapons }}</li>
    <li><strong>Units:</strong> {{ num_units }}</li>
    <li><strong>Available units:</strong> {{ num_units_available }}</li>
    <li><strong>Soldiers:</strong> {{ num_soldiers }}</li>
    <p>You visited this page {{ num_visits }} times.</p>
</ul>
{% endblock %}

weaponry/templates/search.html
{% extends "base.html" %}
{% block content %}
<h1>Search results for "{{query}}":</h1>
</br>
{% if weapons %}
<ul>
{% for weapon in weapons %}
<li>
<a href="{% url 'weapon-detail' weapon.id %}">{{ weapon.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>Nothins was found</p>
{% endif %}
{% endblock %}

weaponry/templates/soldier.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container soldier">
    <h4>{{ soldier.rank }}. {{ soldier.last_name }}, {{ soldier.first_name }}</h4>
    <hr/>
    <p>{{ soldier.description | safe }}</p>

    {% for weapon in soldier.weaponunit_set.all %}
    <hr>
    <p class="{% if weapon.status == 'a' %}text-success{% elif weapon.status == 'n' %}text-danger{% else %}text-warning{% endif %}">
        <strong>{{ weapon.get_status_display }}</strong>
    </p>
    <p class="text-light bg-dark">Weapon: {{ weapon.weapon.name }}</p>
    <p class="text-light bg-dark">Date: {{ weapon.due_back }}</p>
    <p class="text-light bg-dark"><strong>Weapon's serial number: </strong>{{ weapon.id }}</p>
    {% endfor %}
</div>

<div class="content-section">
    <ul>
        {% for weapon in soldier.weaponunit_set.all %}
            <li>
                <a href="{% url 'delete-weapon' soldier.id weapon.id %}">
                    <strong>{{ weapon.weapon.name }}</strong>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

weaponry/templates/soldiers.html
{% extends "base.html" %}

{% block content %}
<h1>Soldiers</h1>
<p>Platoon 1</p>
{% for soldier in soldiers %}
<li><a href="{% url 'soldier' soldier.id %}">
    <strong>{{ soldier.rank }}.  {{ soldier.last_name }}, {{ soldier.first_name }}</strong></a></li>
{% endfor %}
<div class="container puslapiai">
<nav aria-label="...">
{% if soldier.has_other_pages %}
<ul class="pagination pagination-sm justify-content-end">
{% for i in soldier.paginator.page_range %}
{% if soldier.number == i %}
<li class="page-item active">
<a class="page-link" href">{{ i }}</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link" href="?page={{ i }}">{{ i }}</a>
</li>
{% endif %}
{% endfor %}
</ul>
{% endif %}
</nav>
</div>
{% endblock %}

weaponry/templates/weapon_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ weapon.name }}</h1>
<p><strong>Description:</strong> {{ weapon.description | safe }}</p>
<div style="margin-left:20px;margin-top:20px">
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous">

{% endblock %}


</body>

weaponry/templates/weapon_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<h1>Weapon list</h1>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% if weapon_list %}
<div class="row">
    {% for weapon in weapon_list %}
    <div class="col-md4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm" style="width: 14rem;">
            {% if weapon.cover %}
            <img src="{{ weapon.cover.url }}" class="card-img-top">
            {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text"><a class="card-link" href="{{ weapon.id }}">{{ weapon.name }}</a></p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>There are no weapons.</p>
{% endif %}


{% endblock %}